### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by morvy** [thasmo/php.honeypot-blacklist#1]
Hi, I'm trying to implement anti-spam using your script, everything looks fine (it blocks something..) but I get many errors in error.log :/

PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /nfsmnt/_www/lib/Blacklist.php on line 204

I'm calling it like this:
require_once('../lib/Blacklist.php');
$client = new Thasmo\ProjectHoneypot\Blacklist($_SERVER['REMOTE_ADDR'], $data->key);
$result = $client->getResult();

is there something that I do wrong?

**Comment by thasmo** [comment]
I'll have a look at it later.

**Comment by thasmo** [comment]
@morvy, do you maybe call `$client->getResult();` with an argument, like `$client->getResult('activity');` or similar? I've released a new version which fixes the error, which happens if you call `getResult` with an argument while the HTTP:BL API's result doesn't indicate a threat.

**Comment by morvy** [comment]
This is my current function call:
`$ip = $_SERVER['REMOTE_ADDR'];`
`if (!empty($data->key) && filter_var($ip, FILTER_VALIDATE_IP)) {`
`$client = new Thasmo\ProjectHoneypot\Blacklist($ip, $data->key);`
`$result = $client->getResult();`
`if(is_array($result)) {`
I'm thinking if it's a problem related to wrong IP address (IPv4 vs IPv6 ?) because I'm also getting Fatal errors due to my provider as he's crawling my pages within his local network so his IP address (10.10.8.5) throws Invalid IP address error (but this is different story, not important and irrelevant for this issue)

**Comment by thasmo** [comment]
IPv6 addresses won't work because the HTTP:BL API doesn't support them. Can you provide an IP address on which the error occurs so it's reproducable for me? Thanks a lot!

**Comment by morvy** [comment]
Yes, IPv6 cannot work, so I'm filtering only IPv4 (added filter_var option for that), but I receive only that one error regarding `getResult();`
Invalid IP Address is caused by 10.10.8.3 and 10.10.8.5 .. I'll try to also filter private and reserved IPs before calling your magic

**Comment by thasmo** [comment]
You can use a `try/catch` block to handle the invalid IP addresses:

``` php
try {
    $client = new Blacklist('10.10.8.3', 'mykey');
} catch (Exception $exception) {
    print $exception->getMessage();
}
```

Does this solve your problems?

**Comment by morvy** [comment]
Well I don't need to catch errors, I'm just skipping submits if there is a threat detected. if the IP cannot be processed, I won't pass it to Blacklist at all (filter_val). I need to wait for a few hours so the website gets some visits to test those recent changes. But as I wrote, array_key_exists error is not related to Invalid IP Address .. I'll wait for new error and will let you know (updated the script already)

**Comment by thasmo** [comment]
Sure, I just meant you can rely on the Blacklist class to detect invalid IP addresses and don't need to provide your own solution with `filter_var`:

``` php
if (!empty($data->key) {
    $ip = $_SERVER['REMOTE_ADDR'];

    try {
        $client = new Thasmo\ProjectHoneypot\Blacklist($ip, $data->key);
        $result = $client->getResult();
        if (is_array($result)) {
            // BLOCK
        }
    } catch (Exception $e) {}
}
```

**Comment by morvy** [comment]
update: I'm not sure if getResult is directly connected to isSpammer, but I realised that I was also calling isSpammer in other part of page and this was causing the problem with array_key_exists. I didn't change my code only updated yours and it solved those errors, so together with try/catch part, my errorlog is clean again ;) thanks

**Comment by thasmo** [comment]
Awesome, thanks for reporting! Feel free to open a new issue if you need help. Thanks!
